# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=assault --augmentation=none --target-augmentation=0 --seed=0 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=assault --augmentation=none --target-augmentation=0 --seed=1 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=assault --augmentation=none --target-augmentation=0 --seed=2 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 

python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=carnival --augmentation=none --target-augmentation=0 --seed=0 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=carnival --augmentation=none --target-augmentation=0 --seed=1 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=carnival --augmentation=none --target-augmentation=0 --seed=2 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=pong --augmentation=none --target-augmentation=0 --seed=0 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=pong --augmentation=none --target-augmentation=0 --seed=1 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=pong --augmentation=none --target-augmentation=0 --seed=2 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=boxing --augmentation=none --target-augmentation=0 --seed=0 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=boxing --augmentation=none --target-augmentation=0 --seed=1 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
# python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=boxing --augmentation=none --target-augmentation=0 --seed=2 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=skiing --augmentation=none --target-augmentation=0 --seed=0 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=skiing --augmentation=none --target-augmentation=0 --seed=0 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
python3 -m scripts.run --project oorl --entity "slivoviy-barsik_team" --game=skiing --augmentation=none --target-augmentation=0 --seed=0 --momentum-tau=0.01 --dropout=0.5 --spr=0 --jumps=0 --n-steps=100000 --exp="SPR for wo pri episodic_lives=True (rlpyt rb)" --ep-lives=1 --prioritized 0 
    